//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GMCEEntities : DbContext
    {
        public GMCEEntities()
            : base("name=GMCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_Matser> Student_Matser { get; set; }
        public virtual DbSet<Receipt_Master> Receipt_Master { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    
        public virtual ObjectResult<GetAllReceipt_Result> GetAllReceipt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllReceipt_Result>("GetAllReceipt");
        }
    }
}
