//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Master
    {
        public int ID { get; set; }
        public string STDID { get; set; }
        public string Date { get; set; }
        public Nullable<int> Receipt_No { get; set; }
        public Nullable<decimal> PaidFess { get; set; }
        public string FessInWords { get; set; }
        public string Payment_type { get; set; }
    }
}
