//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Matser
    {
        public int ID { get; set; }
        public string Registration_date { get; set; }
        public byte[] Start_date { get; set; }
        public Nullable<int> STD_ID { get; set; }
        public string Student_name { get; set; }
        public string Cource { get; set; }
        public Nullable<int> Student_mobile { get; set; }
        public Nullable<int> Parents_mobile { get; set; }
        public string Total_fees { get; set; }
        public string Fees_Payment { get; set; }
    }
}
